import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FooterWrapper from "@/components/FooterWrapper";
import NavbarWrapper from "@/components/NavbarWrapper";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarWrapper />
        <SpeedInsights />
        <div className="hidden lg:hidden md:flex md:flex-col md:mx-auto items-center justify-center bg-[#166432]">
          <p className="text-white font-extrabold text-2xl">
            This website is only accessible on mobile and desktop devices.
          </p>
        </div>
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
